= Cisco Packet Tracer: Packet Tracer Add new Thing
Julie Sunny Mathew <jsunnymathew@unomaha.edu>
v1.0, 2019-10-10
ifndef::bound[:imagesdir: figs]
:icons: font

This exercise will help to learn about the new Thing that is available in Packet Tracer and how to configure them. 
It will give you the experience in programming the new IoT device.
This chapter will help you to:

  * How to Create and Connect new Thing in Packet Tracer.
  * How to access the programming environment.
  * How to review and modify the existing scripts.

== Learning Objectives

By the end of this lesson, you will be able to:

* Custom Build your own IoT Device.
* Access the programming enviornment and modify and review the existing scripts.

== Packet Tracer - Create Your Own Thing.

Packet Tracer give us the option of creating a new IoT device other than the device already available. There are few prerequisitive for using _Thing_ in Packet Tracer which are:
 * Decide on which new device you need to add.
 * How it will connect to the network and how it will work.
 * Find graphics to represent the beginning and the end state of the device.
 * Identify the existing device which functions similar to the new device so that the existing script can be utilized for the new device.

Lets start understanding the how to create and add new Thing in the smart home network.
In this excercise we will cover chapters 8 of the begineer's course.

**_Chapter 8: Creating and Programming Objects in Packet Tracer_**

This chapter will help you to learn about creating a new smart device in the packet tracer.
Lets understand through the walk-through video and then completing the activity mentioned in the course.

  * Watch the video of _Creating and Connecting a Thing_ mentioned in the 
  _Section 8.1.1.1: Creating and Connecting a Thing._
  * Complete the activity of _Create Your Own Thing_ mentioned in the 
  _Section 8.1.1.2: Packet Tracer: Create Your Own Thing._
  * Watch the video of _Reviewing and Modifying Scripts_ mentioned in the 
  _Section 8.2.1.2: Reviewing and Modifying Scripts._
  * Complete the activity of _Modify existing script for an IoT Thing_ mentioned in the 
  _Section 8.2.1.3: Packet Tracer - Modify existing script for an IoT Thing_


== Thought Questions

=== Basics



=== Do some research


